export const NEWSLETTER_SUBSCRIBE_SUCCESS = "newsletter.SUBSCRIBE_SUCCESS";
export const NEWSLETTER_SUBSCRIBE_FAIL = "newsletter.SUBSCRIBE_FAIL";
export const NEWSLETTER_MESSAGE_CLOSED = "newsletter.MESSAGE_CLOSED";
